version: "3"

services: 
  redis: 
    container_name: redis
    image: redis:6.2-alpine
    ports: 
      - 6379:6379

  db:
    container_name: roleplay-db
    image: postgres:13-alpine
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2204
      - POSTGRES_DB=roleplay_dev
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
  db_test:
    container_name: roleplay-test
    image: postgres:13-alpine
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2204
      - POSTGRES_DB=roleplay_test
    ports:
      - 5423:5432

volumes:
  db:
    driver: local
    