version: "3"

services: 
  redis: 
    container_name: redis
    image: redis
    ports: 
      - 6379:6379

  db:
    container_name: roleplay-db
    image: postgres
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2204
      - POSTGRES_DB=roleplay_dev
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
    